import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "./component/header/Header";
import Footer from "./component/footer/Footer";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
});
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
